---
- name: Create namespace
  kubernetes.core.k8s:
    state: present
    definition:
      api_version: v1
      kind: Namespace
      metadata:
        name: "{{ opensearch.namespace }}"
        labels:
          app: opensearch

- name: Deploy opensearch
  kubernetes.core.k8s:
    state: present
    namespace: "{{ opensearch.namespace }}"
    definition: "{{ lookup('template', '{{ item }}') | from_yaml }}"
  loop: "{{ query('fileglob', 'files/*.yaml') }}"
