---
apiVersion: v1
kind: Service
metadata:
  name: opensearch
  labels:
    app: opensearch
spec:
  selector:
    app: opensearch
  type: ClusterIP
  ports:
  - name: http
    protocol: TCP
    port: 9200
    targetPort: http 
